import os
import shutil
import json
import pickle
from datetime import datetime
from typing import Dict, Any
from src.utils.directory import ensure_directory


class ArtifactExporter:
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.config["output_dir"] = os.path.abspath(config.get("output_dir", "release"))
        self._ensure_output_directory()

    def _ensure_output_directory(self):
        """Ensure output directory exists with proper permissions"""
        release_dir = os.path.join(self.config["output_dir"], "latest")
        os.makedirs(release_dir, exist_ok=True)
        os.chmod(release_dir, 0o777)
        return release_dir

    def export_training_artifacts(
        self, training_results: Dict[str, Any]
    ) -> Dict[str, str]:
        """Export all artifacts to release/latest directory"""
        release_dir = self._ensure_output_directory()
        exported_files = {}

        try:
            # Clear existing contents
            shutil.rmtree(release_dir, ignore_errors=True)
            os.makedirs(release_dir, exist_ok=True)
            os.chmod(release_dir, 0o777)

            artifacts = training_results["artifacts"]

            # Export model files
            model_files = {
                "model.pkl": artifacts.get("model"),
                "metadata.json": artifacts.get("metadata"),
                "metrics.json": artifacts.get("metrics", {}),
                "feature_selector.pkl": artifacts.get("feature_selector"),
                "scaler.pkl": artifacts.get("scaler"),
                "selected_features.json": artifacts.get("selected_features"),
            }

            for filename, src in model_files.items():
                dest = os.path.join(release_dir, filename)
                if src and os.path.exists(src):
                    shutil.copy2(src, dest)
                    os.chmod(dest, 0o644)
                    exported_files[filename.split(".")[0]] = dest
                elif filename == "metrics.json":
                    self._create_default_metrics(release_dir, training_results)
                    exported_files["metrics"] = os.path.join(release_dir, filename)

            # Create supporting files
            self._create_feature_structure(release_dir, training_results)
            self._create_package_info(release_dir, exported_files)

            # Verify all files were created
            for path in exported_files.values():
                if not os.path.exists(path):
                    raise FileNotFoundError(f"Failed to create artifact at {path}")

            return exported_files

        except Exception as e:
            # Clean up partial exports
            shutil.rmtree(release_dir, ignore_errors=True)
            raise RuntimeError(f"Failed to export artifacts: {str(e)}")

    def _create_default_metrics(
        self, release_dir: str, training_results: Dict[str, Any]
    ):
        metrics_path = os.path.join(release_dir, "metrics.json")
        default_metrics = training_results.get(
            "metrics",
            {
                "accuracy": 0,
                "precision": 0,
                "recall": 0,
                "f1": 0,
                "warning": "Metrics not properly saved during training",
            },
        )
        with open(metrics_path, "w") as f:
            json.dump(default_metrics, f, indent=2)
        os.chmod(metrics_path, 0o644)

    def _create_feature_structure(
        self, release_dir: str, training_results: Dict[str, Any]
    ):
        features_path = os.path.join(release_dir, "feature_structure.json")
        feature_structure = {
            "feature_names": training_results.get("selected_features", []),
            "required_features": len(training_results.get("selected_features", [])),
            "version": datetime.now().strftime("%Y%m%d_%H%M%S"),
        }
        with open(features_path, "w") as f:
            json.dump(feature_structure, f, indent=2)
        os.chmod(features_path, 0o644)

    def _create_package_info(self, release_dir: str, files: Dict[str, str]):
        info_path = os.path.join(release_dir, "package_info.json")
        package_info = {
            "created_at": datetime.now().isoformat(),
            "contents": {k: os.path.basename(v) for k, v in files.items()},
            "notes": "Automatically generated by spyware-detector-training pipeline",
        }
        with open(info_path, "w") as f:
            json.dump(package_info, f, indent=2)
        os.chmod(info_path, 0o644)
